spring:
  profiles:
    include: oauth

  session:
    store-type: jdbc

  datasource:
    url: jdbc:mysql://localhost:3306/archiveB?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111111111
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/test
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
  prefix: classpath:/templates/, classpath:/static/
  suffix: .html

logging.level:
  org.springframework: debug
  org.springframework.web: debug
  org.hibernate.SQL: debug
